import { AiOutlineCheck } from "react-icons/ai";
import { BiTime } from "react-icons/bi";
import {
  BsBookmarkHeart,
  BsChevronDown,
  BsChevronLeft,
  BsChevronRight,
  BsCursorText,
  BsDiagram3,
  BsEnvelope,
  BsEnvelopeFill,
  BsEye,
  BsFolder,
  BsGear,
  BsGrid,
  BsHouseDoor,
  BsImages,
  BsMap,
  BsPeopleFill,
  BsPersonX,
  BsPinMap,
  BsSearch,
  BsTelephoneFill,
  BsTrash,
  BsWindow,
} from "react-icons/bs";
import { FaFacebook, FaInstagram, FaLinkedin, FaYoutube } from "react-icons/fa";
import { FiMenu } from "react-icons/fi";
import { IoMdPricetag, IoMdSend } from "react-icons/io";
import { MdLocationPin } from "react-icons/md";

export const ICONS = {
  MENU: FiMenu,
  Envelope: BsEnvelope,
  Favorite: BsBookmarkHeart,
  Posted: BsFolder,
  SignOut: BsPersonX,
  Settings: BsGear,
  Delete: BsTrash,
  Eye: BsEye,
  House: BsHouseDoor,
  Category: BsGrid,
  Map: BsMap,
  Surface: BsPinMap,
  Watch: BiTime,
  Search: BsSearch,
  Check: AiOutlineCheck,
  CHEVRON_DOWN: BsChevronDown,
  CHEVRON_RIGHT: BsChevronRight,
  CHEVRON_LEFT: BsChevronLeft,
  Price: IoMdPricetag,
  Text: BsCursorText,
  Photo: BsImages,
  SEND: IoMdSend,
  Admin: BsWindow,
  Scrap: BsDiagram3,
  Users: BsPeopleFill,
  EMAIL: BsEnvelopeFill,
  LOCATION: MdLocationPin,
  PHONE: BsTelephoneFill,

  FACEBOOK: FaFacebook,
  YOUTUBE: FaYoutube,
  LINKEDIN: FaLinkedin,
  INSTAGRAM: FaInstagram,
};
